CREATE TABLE serial_numbers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    SerialNumber VARCHAR(10) UNIQUE NOT NULL,
    KodePartner VARCHAR(50) NOT NULL,
    Keterangan TEXT,
    RecordOwnerID VARCHAR(50),
    CreatedBy VARCHAR(100),
    UpdatedBy VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
